### ISSUE TITLE
对于 req.header('ts') 的疑问

### ISSUE THREAD

**Issue by Truke** [xiaozhongliu/node-api-seed#1]
const accessToken = await jwtSvc.sign({ username }) 这儿是创建的token
登录成功后发送给前台了 
在验证token的时候 
`
const stamp = req.header('ts')
const token = req.header('token')
if (token && stamp && checkToken(token, stamp)) {
    return next()
}

function checkToken(token, stamp) {
    return hash(HASHED_TOKEN + stamp) === token
}
`
请问 ts 是怎么被赋值的？

**Comment by xiaozhongliu** [comment]
刚刚更新了wiki, 里面有postman直接可以跑起来调的, 你可以试试:
https://github.com/xiaozhongliu/node-api-seed/wiki#%E9%A1%B9%E7%9B%AE%E9%A6%96%E6%AC%A1%E8%BF%90%E8%A1%8C

另外, 这个项目还在更新, 建议不要fork, 直接拉源码.
